/********************************************************************************
 * Copyright (c) 2025 Xored Software Inc and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Xored Software Inc - initial API and implementation
 ********************************************************************************/
def build
node {
  checkout scm
  result = load('releng/Jenkinsfile.groovy')(this)
  assert result != null
  build = result
}

pipeline {
  agent {
    kubernetes {
      yaml build.YAML_BUILD_AND_DEPLOY_AGENT
    }
  }

  options {
     timestamps()
     buildDiscarder(logRotator(numToKeepStr: '30', daysToKeepStr: '10'))
     disableConcurrentBuilds()
     timeout(time: 10, unit: 'HOURS')
  }

  stages {
    stage('Start Build and Test') {
      steps {
        script {
          build.build_and_test(true)
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          build.deploy("Nightly")
        }
      }
    }
  }

  post {
    always {
      script {
        build.post_build_actions()
      }
    }
  }
}
