def build
node {
  checkout scm
  result = load('releng/Jenkinsfile.groovy')(this)
  assert result != null
  build = result
}

pipeline {
  agent {
    kubernetes {
      yaml build.YAML_BUILD_AND_DEPLOY_AGENT
    }
  }

  options {
     buildDiscarder(logRotator(numToKeepStr: '30', daysToKeepStr: '10'))
     disableConcurrentBuilds()
     timeout(time: 10, unit: 'HOURS')
  }

  stages {
    stage('Start Build and Test') {
      steps {
        script {
          build.build_and_test(true)
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          build.deploy("Nightly")
        }
      }
    }
  }

  post {
    always {
      script {
        build.post_build_actions()
      }
    }
  }
}
