/********************************************************************************
 * Copyright (c) 2025 Xored Software Inc and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Xored Software Inc - initial API and implementation
 ********************************************************************************/
def build
node {
  checkout scm
  result = load('releng/Jenkinsfile.groovy')(this)
  assert result != null
  build = result
}


pipeline {
  agent {
    kubernetes {
      yaml build.YAML_BUILD_AND_DEPLOY_AGENT
    }
  }

  parameters {
    choice(name: 'MODE', choices: ['Release', 'Milestone'], description: 'The deploy mode')
    string(name: 'MILESTONE_VERSION', defaultValue: 'MO', description: 'Only for milestone build')
  }
  options {
     buildDiscarder(logRotator(numToKeepStr: '3', daysToKeepStr: '10'))
     disableConcurrentBuilds()
     timeout(time: 10, unit: 'HOURS')
  }

  stages {
    stage('Start Build and Test') {
      steps {
        script {
          if(params.MODE == 'Milestone') {
            build.set_milestone(params.MILESTONE_VERSION)
          }
          build.build_and_test(true)
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          build.deploy(params.MODE, params.MILESTONE_VERSION)
        }
      }
    }
  }

  post {
    always {
      script {
        build.post_build_actions()
      }
    }
  }
}
