/********************************************************************************
 * Copyright (c) 2025 Xored Software Inc and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Xored Software Inc - initial API and implementation
 ********************************************************************************/
def build = library(
  identifier: 'rcptt-pipeline-library@groovy',
  retriever: modernSCM(
    [
      $class: 'GitSCMSource',
      remote: 'https://github.com/xored/rcptt.git'
    ]
  )
).org.eclipse.rcptt.jenkins.Build.new(this)

pipeline {
  agent {
    kubernetes {
      label 'rcptt-build-agent-3.5.4'
      yaml build.YAML_BUILD_AGENT
    }
  }

  stages {
    stage('Start Test') {
      steps {
        script {
          build.tests(TESTS, RUNNER, ARGS)
        }
      }
    }
  }

  post {
    always {
      script {
        build.post_build_actions()
      }
    }
  }
}