name: Verify branch
on:
- workflow_dispatch
- push
- pull_request
permissions:
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: basilevs/ubuntu-rcptt:3.7.3 
      env:
        DISPLAY: :1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: m2repository
          path: |
            /root/.m2/repository
      - name: VNC
        run: vncserver $DISPLAY -localhost=1 -noxstartup -PasswordFile /root/.vnc/passwd
      - name: Maven and Java version
        run: mvn --version
      - name: Maven local repo location
        run: mvn --quiet --non-recursive help:evaluate -Dtycho.mode=maven -DforceStdout -Dexpression='settings.localRepository'
      - name: Build
        run: ./build.sh -Dmaven.repo.local=`pwd`/m2 -DforceContextQualifier=`date '+%Y%m%d%H%M'` --errors --batch-mode --no-transfer-progress
      - name: List all files
        if: always()
        run: find . > files.txt
      - name: Archive results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: build_results
          include-hidden-files: true
          path: |
            files.txt
            **/target/**/*.log
            **/target/**/*.info
            **/target/**/*.ini
            **/*.hrpof
      - name: Archive update site
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: repository
          path: 'repository/rcptt/target/repository/**'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386 # v6.4.0
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/*-reports/*.xml'
          fail_on_failure: false
          annotate_only: true
      - name: Archive Runner
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: runner
          path: runner/product/target/products/org.eclipse.rcptt.runner.headless-linux.gtk.x86_64.zip
      - name: Archive Maven Plugin
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: maven-plugin
          path: m2/org/eclipse/rcptt/rcptt-*/**
      - name: Archive IDE
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: ide
          path: repository/full/target/products/org.eclipse.rcptt.platform.product-linux.gtk.x86_64.zip
